language: node_js
cache:
  directories:
    - node_modules
node_js:
  - '10'
  - '9'
  - '8'
sudo: false
before_script:
  - npm prune
script:
  - npm run test:cover
after_success:
  - npm run test:cover:report
